<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Audit trail of delivery documents generated by admins: who exported what,
 * when. Drives the "Exported" badge and the "needs slips" filter.
 *
 * type: slip (one seller sub-order) | slips (every sub-order of an order)
 *       | summary (internal admin summary) | bulk (several orders at once —
 *       one row is written per order)
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('order_exports', function (Blueprint $table) {
            $table->id();
            $table->foreignId('order_id')->constrained('orders')->cascadeOnDelete();
            $table->foreignId('seller_order_id')->nullable()->constrained('seller_orders')->nullOnDelete();
            $table->string('type', 16);
            $table->foreignId('exported_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('created_at')->useCurrent();

            $table->index(['order_id', 'type']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('order_exports');
    }
};
