<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * One delivery document generated by an admin (see order_exports migration).
 */
class OrderExport extends Model
{
    const UPDATED_AT = null;

    const TYPE_SLIP    = 'slip';     // one seller sub-order
    const TYPE_SLIPS   = 'slips';    // every sub-order of the order
    const TYPE_SUMMARY = 'summary';  // internal admin summary
    const TYPE_BULK    = 'bulk';     // slips of several orders in one PDF

    /** Types that mean "the courier has the paperwork". */
    const SLIP_TYPES = [self::TYPE_SLIP, self::TYPE_SLIPS, self::TYPE_BULK];

    protected $fillable = ['order_id', 'seller_order_id', 'type', 'exported_by'];

    protected $casts = ['created_at' => 'datetime'];

    public function order()
    {
        return $this->belongsTo(Order::class);
    }

    public function exporter()
    {
        return $this->belongsTo(User::class, 'exported_by');
    }
}
